import type { LayoutModuleSpec } from './types'

export const IMPLEMENTED_LAYOUT_MODULES = [
  'callout',
  'hero',
  'cards',
  'metrics',
  'steps',
  'timeline',
  'verdict',
  'quote',
  'image-text',
  'faq',
] as const

const implemented = new Set<string>(IMPLEMENTED_LAYOUT_MODULES)

const specs = [
  {
    name: 'hero',
    category: 'opening',
    bodyFormat: 'fields',
    renderer: 'hero',
    requiredFields: ['title'],
    optionalFields: ['eyebrow', 'subtitle', 'meta'],
    variants: ['default', 'quiet', 'accent'],
    description: 'Opening block for the main judgment and reading entrance.',
  },
  {
    name: 'toc',
    category: 'opening',
    bodyFormat: 'rows',
    renderer: 'toc',
    minColumns: 2,
    columns: ['label', 'title', 'description'],
    description: 'Compact table of contents for long notes.',
  },
  {
    name: 'cards',
    category: 'opening',
    bodyFormat: 'rows',
    renderer: 'cards',
    minColumns: 2,
    columns: ['title', 'description', 'meta', 'variant'],
    variants: ['default', 'subtle', 'accent'],
    description: 'Small grouped cards for sections, options, or themes.',
  },
  {
    name: 'part',
    category: 'opening',
    bodyFormat: 'fields',
    renderer: 'part',
    requiredFields: ['title'],
    optionalFields: ['label', 'subtitle'],
    description: 'Large section divider for major document parts.',
  },
  {
    name: 'label-title',
    category: 'opening',
    bodyFormat: 'fields',
    renderer: 'label-title',
    requiredFields: ['title'],
    optionalFields: ['label', 'subtitle'],
    description: 'Compact label plus title block.',
  },
  {
    name: 'metrics',
    category: 'infographic',
    bodyFormat: 'rows',
    renderer: 'metrics',
    minColumns: 3,
    columns: ['label', 'value', 'description'],
    description: 'Metric grid for compact quantitative summaries.',
  },
  {
    name: 'compare',
    category: 'infographic',
    bodyFormat: 'rows',
    renderer: 'compare',
    minColumns: 3,
    columns: ['item', 'left', 'right'],
    description: 'Side-by-side comparison rows.',
  },
  {
    name: 'steps',
    category: 'infographic',
    bodyFormat: 'rows',
    renderer: 'steps',
    minColumns: 2,
    columns: ['title', 'description', 'meta'],
    description: 'Ordered process or action sequence.',
  },
  {
    name: 'timeline',
    category: 'infographic',
    bodyFormat: 'rows',
    renderer: 'timeline',
    minColumns: 2,
    columns: ['time', 'title', 'description'],
    description: 'Time-ordered milestones or events.',
  },
  {
    name: 'infographic',
    category: 'infographic',
    bodyFormat: 'fields',
    renderer: 'infographic',
    requiredFields: ['title'],
    optionalFields: ['summary', 'value'],
    description: 'Single visual summary block.',
  },
  {
    name: 'verdict',
    category: 'judgment',
    bodyFormat: 'fields',
    renderer: 'verdict',
    requiredFields: ['title'],
    optionalFields: ['summary', 'confidence', 'status'],
    variants: ['default', 'success', 'warning', 'danger'],
    description: 'Decision or judgment block.',
  },
  {
    name: 'audience-fit',
    category: 'judgment',
    bodyFormat: 'rows',
    renderer: 'audience-fit',
    minColumns: 2,
    columns: ['audience', 'fit', 'reason'],
    description: 'Who this fits and why.',
  },
  {
    name: 'myth-fact',
    category: 'judgment',
    bodyFormat: 'rows',
    renderer: 'myth-fact',
    minColumns: 2,
    columns: ['myth', 'fact', 'reason'],
    description: 'Myth versus fact explanation.',
  },
  {
    name: 'manifesto',
    category: 'judgment',
    bodyFormat: 'rows',
    renderer: 'manifesto',
    minColumns: 1,
    columns: ['principle', 'detail'],
    description: 'Principle list for a strong point of view.',
  },
  {
    name: 'bridge',
    category: 'judgment',
    bodyFormat: 'fields',
    renderer: 'bridge',
    requiredFields: ['from', 'to'],
    optionalFields: ['why'],
    description: 'Transition from one mental model to another.',
  },
  {
    name: 'quote',
    category: 'evidence',
    bodyFormat: 'fields',
    renderer: 'quote',
    requiredFields: ['text'],
    optionalFields: ['source', 'url'],
    description: 'Quoted evidence with optional source.',
  },
  {
    name: 'image-text',
    category: 'evidence',
    bodyFormat: 'fields',
    renderer: 'image-text',
    requiredFields: ['image'],
    optionalFields: ['title', 'text', 'alt'],
    variants: ['default', 'reverse'],
    description: 'Image plus explanatory text.',
  },
  {
    name: 'image-compare',
    category: 'evidence',
    bodyFormat: 'fields',
    renderer: 'image-compare',
    requiredFields: ['before', 'after'],
    optionalFields: ['title', 'caption'],
    description: 'Before and after image comparison.',
  },
  {
    name: 'image-annotate',
    category: 'evidence',
    bodyFormat: 'json_object',
    renderer: 'image-annotate',
    description: 'Annotated image evidence.',
  },
  {
    name: 'image-steps',
    category: 'evidence',
    bodyFormat: 'json_array',
    renderer: 'image-steps',
    description: 'Image sequence with step captions.',
  },
  {
    name: 'cta',
    category: 'conversion',
    bodyFormat: 'fields',
    renderer: 'cta',
    requiredFields: ['title'],
    optionalFields: ['description', 'action'],
    description: 'Private or team knowledge-base call to action.',
  },
  {
    name: 'faq',
    category: 'conversion',
    bodyFormat: 'rows',
    renderer: 'faq',
    minColumns: 2,
    columns: ['question', 'answer'],
    description: 'Question and answer list.',
  },
  {
    name: 'checklist',
    category: 'conversion',
    bodyFormat: 'rows',
    renderer: 'checklist',
    minColumns: 1,
    columns: ['item', 'state'],
    description: 'Read-only checklist.',
  },
  {
    name: 'cases',
    category: 'conversion',
    bodyFormat: 'rows',
    renderer: 'cases',
    minColumns: 2,
    columns: ['case', 'result', 'note'],
    description: 'Case examples.',
  },
  {
    name: 'summary',
    category: 'conversion',
    bodyFormat: 'fields',
    renderer: 'summary',
    requiredFields: ['title'],
    optionalFields: ['body'],
    description: 'End summary block.',
  },
  {
    name: 'notice',
    category: 'conversion',
    bodyFormat: 'fields',
    renderer: 'notice',
    requiredFields: ['text'],
    optionalFields: ['title'],
    description: 'Small notice block.',
  },
  {
    name: 'logos',
    category: 'conversion',
    bodyFormat: 'rows',
    renderer: 'logos',
    minColumns: 1,
    columns: ['name', 'meta'],
    description: 'Restrained logo or name row.',
  },
  {
    name: 'pricing',
    category: 'conversion',
    bodyFormat: 'rows',
    renderer: 'pricing',
    minColumns: 3,
    columns: ['plan', 'price', 'note'],
    description: 'Private evaluation pricing table.',
  },
  {
    name: 'specs',
    category: 'conversion',
    bodyFormat: 'rows',
    renderer: 'specs',
    minColumns: 2,
    columns: ['name', 'value', 'note'],
    description: 'Specification list.',
  },
  {
    name: 'toolbox',
    category: 'conversion',
    bodyFormat: 'rows',
    renderer: 'toolbox',
    minColumns: 2,
    columns: ['tool', 'use', 'link'],
    description: 'Tools and references.',
  },
  {
    name: 'author-card',
    category: 'brand',
    bodyFormat: 'fields',
    renderer: 'author-card',
    requiredFields: ['name'],
    optionalFields: ['role', 'bio'],
    description: 'Author or owner context.',
  },
  {
    name: 'subscribe',
    category: 'brand',
    bodyFormat: 'fields',
    renderer: 'subscribe',
    requiredFields: ['title'],
    optionalFields: ['description'],
    description: 'Private follow or subscription prompt.',
  },
  {
    name: 'people',
    category: 'brand',
    bodyFormat: 'rows',
    renderer: 'people',
    minColumns: 2,
    columns: ['name', 'role', 'note'],
    description: 'People involved in a topic.',
  },
  {
    name: 'series',
    category: 'brand',
    bodyFormat: 'rows',
    renderer: 'series',
    minColumns: 2,
    columns: ['title', 'status', 'path'],
    description: 'Series navigation for related notes.',
  },
  {
    name: 'callout',
    category: 'enhanced',
    bodyFormat: 'rows',
    renderer: 'callout',
    aliases: ['admonition', 'note'],
    modifiers: ['note', 'tip', 'info', 'warning', 'danger'],
    minColumns: 1,
    columns: ['content'],
    description: 'Docusaurus-style admonition block with Journal styling.',
  },
  {
    name: 'definition',
    category: 'enhanced',
    bodyFormat: 'json_object',
    renderer: 'definition',
    description: 'Term and definition object.',
  },
  {
    name: 'quote-card',
    category: 'enhanced',
    bodyFormat: 'fields',
    renderer: 'quote-card',
    requiredFields: ['quote'],
    optionalFields: ['source'],
    description: 'Card-style quote.',
  },
  {
    name: 'tweet',
    category: 'enhanced',
    bodyFormat: 'fields',
    renderer: 'tweet',
    requiredFields: ['text'],
    optionalFields: ['author', 'url'],
    description: 'Read-only social post excerpt.',
  },
  {
    name: 'stat-row',
    category: 'enhanced',
    bodyFormat: 'json_array',
    renderer: 'stat-row',
    description: 'Dense statistic row.',
  },
  {
    name: 'question',
    category: 'enhanced',
    bodyFormat: 'fields',
    renderer: 'question',
    requiredFields: ['text'],
    optionalFields: ['context'],
    description: 'Question block.',
  },
  {
    name: 'resource-list',
    category: 'enhanced',
    bodyFormat: 'json_array',
    renderer: 'resource-list',
    description: 'Structured resource list.',
  },
  {
    name: 'comparison-table',
    category: 'enhanced',
    bodyFormat: 'json_object',
    renderer: 'comparison-table',
    description: 'Structured comparison table.',
  },
  {
    name: 'changelog',
    category: 'enhanced',
    bodyFormat: 'json_array',
    renderer: 'changelog',
    description: 'Changelog entries.',
  },
] satisfies Array<Omit<LayoutModuleSpec, 'implemented'>>

export const JOURNAL_LAYOUT_MODULES: readonly LayoutModuleSpec[] = specs.map((spec) => ({
  ...spec,
  implemented: implemented.has(spec.name),
}))

const moduleByName = new Map<string, LayoutModuleSpec>()
const aliasByName = new Map<string, string>()

for (const spec of JOURNAL_LAYOUT_MODULES) {
  moduleByName.set(spec.name, spec)
  for (const alias of spec.aliases ?? []) {
    aliasByName.set(alias, spec.name)
  }
}

export function resolveLayoutModuleName(name: string): string | undefined {
  const normalized = name.trim().toLowerCase()
  if (moduleByName.has(normalized)) return normalized
  return aliasByName.get(normalized)
}

export function getLayoutModuleSpec(name: string): LayoutModuleSpec | undefined {
  const canonical = resolveLayoutModuleName(name)
  return canonical ? moduleByName.get(canonical) : undefined
}
